default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tutorbox-api_development
  port: 5440
  user: postgres
  password: password

test:
  <<: *default
  database: tutorbox-api_test
  port: 5440
  user: postgres
  password: password

production:
  <<: *default
  database: tutorbox-api_production
  username: tutorbox-api
  password: <%= ENV['TUTORBOX-API_DATABASE_PASSWORD'] %>
